# Generated by Django 3.0.1 on 2019-12-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
