# Generated by Django 2.2.7 on 2020-01-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
