# Generated by Django 3.0.1 on 2019-12-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0002_auto_20191225_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='SId',
            new_name='reg_roll',
        ),
    ]
